language: php
php:
  - 5.4
  - 5.6
branches:
  only:
    - dev
before_script:
  - composer self-update
  - composer install
  - "mysql -utravis -e 'create database if not exists `db_aperoLaravel`';"
script:
  - vendor/bin/phpunit
